
export const data = [
  {
    id: 1,
    image: require("../assets/musculosanegra.png"),
    name: "Musculosa Negra",
    href: '#',
    imageAlt: "Black Shirt.",
    stock: 5,
    min:1,
    price: "$2000",
    description: "Musculosa negra de la primera barra de cordoba. Producto de algodon sin poliester, de excelente calidad para disfrutar de todo el verano. En todos los talles disponibles",
    category: "Musculosas",
  },
  {
    id: 2,
    image: require("../assets/musculosaroja.png"),
    name: "Musculosa Roja",
    href: '#',
    imageAlt: "Red Shirt.",
    stock: 5,
    min:1,
    price: "$2000",
    description: "Musculosa Roja de la primera barra de cordoba. Producto de algodon sin poliester, de excelente calidad para disfrutar de todo el verano. En todos los talles disponibles",
    category: "Musculosas",
  },
  {
    id: 3,
    image: require("../assets/short.png"),
    name: "Short negro",
    href: '#',
    imageAlt: "Black Short.",
    stock: 5,
    min:1,
    price: "$2000",
    description: "Short negro de la primera barra de cordoba. Producto de algodon sin poliester, de excelente calidad para disfrutar de todo el verano. En todos los talles disponibles",
    category: "Short",
  },
];
